---
- name: Install KIND
  hosts: localhost
  become: yes
  become_user: root
  tasks:

    - name: Download kind binary
      command: curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.17.0/kind-linux-amd64

    - name: Make kind executable
      command: sudo chmod +x ./kind

    - name: Move kind to PATH
      command: sudo mv ./kind /usr/local/bin/kind

    - name: Create kind cluster
      command: sudo kind create cluster
