apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  selector:
    app: clickhouse
  ports:
  - name: tcp
    port: 9000
    targetPort: 9000
  type: ClusterIP
