apiVersion: v1
kind: Pod
metadata:
  name: nginx
#  labels:
#    role: myrole
spec:
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - name: nginx-port
          containerPort: 80
          protocol: TCP
