apiVersion: batch/v1
kind: CronJob
metadata:
  name: busybox-cron-job
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: busybox
            image: busybox
            command: ["sh", "-c", "date"]
          restartPolicy: OnFailure
