apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ns1
  namespace: ns1
spec:
  selector:
    matchLabels:
      app: nginx-ns1
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-ns1
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
