---
- name: Kryje detyren e djeshit me terraform
  hosts:
    - local
  tasks:
  - name: Beja init
    ansible.builtin.command: chdir=/life/Terra_Kafka terraform init
  - name: Beja njehere destroy nese ekziston
    ansible.builtin.command: chdir=/life/Terra_Kafka terraform destroy -auto-approve
  - name: Beja apply
    ansible.builtin.command: chdir=/life/Terra_Kafka terraform apply -auto-approve
