---
- name: Kryje detyren e djeshit me terraform
  hosts:
    - local
  tasks:
  - name: Shko te follderi i detyres
    ansible.builtin.command: chdir=/life/Ushtrime terraform init
#  - name: Beja init
 #   ansible.builtin.command: terraform init
  - name: Beja njehere destroy nese ekziston
    ansible.builtin.command: chdir=/life/Ushtrime terraform destroy -auto-approve
  - name: Beja apply
    ansible.builtin.command: chdir=/life/Ushtrime terraform apply -auto-approve
