apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - name: busy-box
      image: registry.k8s.io/busybox
      command: [ "sleep", "3600"]
      env:
        - name: var1
          value: "Good morning"
        - name: var2
          value: "Good afternoon"
        - name: var3
          value: "Good evening"
  restartPolicy: Never
