apiVersion: v1
kind: Pod
metadata:
  name: node-selector-box
spec:
  nodeName: kinder-worker2
  tolerations:
  - key: life
    operator: Equal
    value: gjirafa
    effect: NoExecute
  - key: gjirafa
    operator: Equal
    value: life
    effect: NoSchedule
  containers:
    - name: busy-box
      image: registry.k8s.io/busybox
      command: [ "sleep", "3600"]
