apiVersion: v1
kind: Pod
metadata:
  name: pgadmin-pod
  labels:
    app: pgadmin
spec:
  containers:
  - name: pgadmin
    image: dpage/pgadmin4
    env:
    - name: PGADMIN_DEFAULT_EMAIL
      valueFrom:
        secretKeyRef:
          name: pgadmin-secret
          key: pgadmin-user
    - name: PGADMIN_DEFAULT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: pgadmin-secret
          key: pgadmin-pass
  restartPolicy: Always
