apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx5
  name: nginx5
spec:
  containers:
  - image: nginx:alpine
    name: nginx5
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
