apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-echo
  template:
    metadata:
      labels:
        app: app-echo
    spec:
      containers:
      - name: app-v1
        image: hashicorp/http-echo
        args:
         - "-text=app-v1"
        ports:
#        - containerPort: 5678
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-echo
  template:
    metadata:
      labels:
        app: app-echo
    spec:
      containers:
      - name: app-v2
        image: hashicorp/http-echo
        args:
         - "-text=app-v2"
        ports:
#        - containerPort: 5678
---
kind: Service
apiVersion: v1
metadata:
  name: app-svc
spec:
  type: LoadBalancer
  selector:
    app: app-echo
  ports:
    - port: 80
      targetPort: 5678
  trafficShift:
    - cluster: app-v1
      weight: 75
    - cluster: app-v2
      weight: 25
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / $1
spec:
  rules:
  - http:
      paths:
      - path: /apps
        pathType: Prefix
        backend:
          service:
            name: app-svc
            port:
              number: 80
