apiVersion: v1
kind: Pod
metadata:
  name: nginx-vol
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-vol
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-volume
      mountPath: /etc/cfg
  volumes:
  - name: nginx-volume
    configMap:
      name: cfgvolume
