apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sh"
      - "-c"
      - "touch /tmp/ready; echo 'Ready!' >> /tmp/ready; sleep 120; rm /tmp/ready"
    readinessProbe:
      exec:
        command:
          - "cat"
          - "/tmp/ready"
      initialDelaySeconds: 5
      periodSeconds: 5
