apiVersion: v1
kind: Pod
metadata:
  name: busy-box
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "cat"
      - "/data/message"
    volumeMounts:
    - name: configmap-volume
      mountPath: /data
  volumes:
  - name: configmap-volume
    configMap:
      name: busybox-configmap
