apiVersion: v1
kind: Pod
metadata:
  name: busybox-pods
spec:
  containers:
  - name: writer
    image: busybox
    command:
      - "sh"
      - "-c"
      - "echo 'Hello World' > /data/message"
    volumeMounts:
    - name: data-volume
      mountPath: /data
  - name: reader
    image: busybox
    command:
      - "cat"
      - "/data/message"
    volumeMounts:
    - name: data-volume
      mountPath: /data
  volumes:
  - name: data-volume
    emptyDir: {}
