apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
  - name: nginx
    image: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
    - name: volumibb
      mountPath: /var/log/nginx/
  - name: busybox
    image: busybox
    command: ["sh","-c","tail -f /var/log/nginx/access.log", "sleep 30"]
    volumeMounts:
    - name: volumibb
      mountPath: /var/log/nginx/
  volumes:
  - name: volumibb
    emptyDir: {}
